# Tensorflow basic

In [1]:
import tensorflow as tf
print(tf.__version__)

/Users/lywang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.10.0


## Lazy evaluation

In [2]:
# tensorflow draws a "Directed Acyclic Graph (DAG)"  
# tf nodes represent data or operations.
a = tf.constant([1, 2, 3])
b = a + a 
print(a) # data
print(b) # operation

Tensor("Const:0", shape=(3,), dtype=int32)
Tensor("add:0", shape=(3,), dtype=int32)


In [3]:
# evaluate a graph to get values in nodes
c = tf.constant([1, 2, 3], name='my_node_c')
with tf.Session() as ss:
    result = ss.run(c)
    
print(c)      # still a tf node (even after run in a session), name assigned
print(result) # value

Tensor("my_node_c:0", shape=(3,), dtype=int32)
[1 2 3]


In [4]:
a = tf.constant([1, 2, 3])
b = tf.Variable([2, 4, 6])  # initial value for variable
c = tf.add(b, a) 
with tf.Session() as ss:
    ss.run(tf.global_variables_initializer()) # probably always need this
    result = ss.run(c)
print(c)
print(result)

Tensor("Add_1:0", shape=(3,), dtype=int32)
[3 6 9]


note: tf.get_variable is preferred over tf.Variable in nn 

## data type issue

In [5]:
a = tf.Variable([1, 2, 3])
b = tf.Variable([1, 2, 3]) # change to tf.Variable([1, 2, 3.0]) will cause an error
c = a + b
with tf.Session() as ss:
    ss.run(tf.global_variables_initializer()) # probably always need this
    result = ss.run(c)
print(result)

[2 4 6]
